runtime: nodejs14  # Ganti dengan versi runtime Node.js yang sesuai

instance_class: F1  # Ganti dengan tipe instance yang sesuai

handlers:
- url: /img
  static_dir: public/img

- url: /style.css
  static_files: public/style.css
  upload: public/style.css

- url: /index.html
  static_files: public/index.html
  upload: public/index.html

- url: /.*
  script: auto
